# Generated by Django 2.2.1 on 2019-06-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.CharField(max_length=200)),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
